python f_tune.py \
  --output_dir=output \
  --model_type=gpt2-xl \
  --model_name_or_path=gpt2-xl \
  --do_train \
  --train_data_file=./sciq/train.txt \
  --do_eval \
  --eval_data_file=./sciq/test.txt \
  --per_gpu_train_batch_size 2 \
  --num_train_epochs 1 \
  --warmup_steps 1